### ISSUE TITLE
Implement Liveness and Readiness Probes for Web App

### ISSUE THREAD

**Issue by prasadhonrao** [prasadhonrao/sportiverse#18]
**Description:**
We need to add **liveness** and **readiness** probes for the Web App in the Kubernetes deployment configuration to ensure better monitoring, automatic restarts, and availability checks.

**Tasks:**
- Add **liveness probe** to the Kubernetes deployment configuration to check if the web app is running and responsive. If the liveness probe fails, Kubernetes will automatically restart the container.
- Add **readiness probe** to ensure that the web app is fully initialized and ready to accept traffic before it is added to the service load balancer.

**Requirements:**
- The probes should not require any changes to the app code. They should be simple HTTP GET requests to the `/health` endpoint (or similar).
- If the app does not expose a `/health` endpoint, we can configure a dummy health check that returns `200 OK` in NGINX.

**Proposed Solution:**
1. **Liveness Probe:** Checks if the web app is alive by sending a GET request to `/health`. If the probe fails, Kubernetes should restart the container.
2. **Readiness Probe:** Checks if the web app is ready to serve traffic, ideally checking the `/health` endpoint as well, but could be adjusted based on app behavior.
3. Configure these probes in the Kubernetes `Deployment` YAML for the web app container.

**Example of Kubernetes Deployment with Probes:**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportiverse-webapp-deployment
  namespace: sportiverse-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportiverse-webapp
  template:
    metadata:
      labels:
        app: sportiverse-webapp
    spec:
      containers:
        - name: sportiverse-webapp-container
          image: prasadhonrao/sportiverse-webapp:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
```

**Additional Context:**
- This issue will help with automatic recovery of the web app in case it becomes unresponsive.
- The `/health` endpoint could be served using a configuration in NGINX or implemented in the app itself.
