### ISSUE TITLE
Implement Liveness and Readiness Probes for Web API

### ISSUE THREAD

**Issue by prasadhonrao** [prasadhonrao/sportiverse#19]
**Description:**
We need to add **liveness** and **readiness** probes for the Web API in the Kubernetes deployment configuration to improve monitoring, ensure the application is healthy, and automate restarts when required.

**Tasks:**
- Add **liveness probe** to the Kubernetes deployment configuration to check if the Web API is running and responsive. If the liveness probe fails, Kubernetes should automatically restart the container.
- Add **readiness probe** to ensure that the Web API is fully initialized and ready to serve traffic before it is added to the service load balancer.

**Requirements:**
- The probes should perform HTTP GET requests to a `/health` or similar endpoint to check the health status.
- If the Web API does not expose a `/health` endpoint, we can set up a dummy health check returning a `200 OK` response via NGINX or another service.

**Proposed Solution:**
1. **Liveness Probe:** It will send a GET request to `/health` to check if the Web API is running. If the Web API is unresponsive or failing, the container will be restarted by Kubernetes.
2. **Readiness Probe:** This will check if the Web API is ready to accept traffic. The probe will also use `/health` but with adjusted timings to allow for app initialization.
3. Configure these probes in the Kubernetes `Deployment` YAML for the Web API container.

**Example of Kubernetes Deployment with Probes:**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportiverse-webapi-deployment
  namespace: sportiverse-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportiverse-webapi
  template:
    metadata:
      labels:
        app: sportiverse-webapi
    spec:
      containers:
        - name: sportiverse-webapi-container
          image: prasadhonrao/sportiverse-webapi:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
```

**Additional Context:**
- This issue will help the Kubernetes cluster automatically restart the Web API if it becomes unresponsive.
- The `/health` endpoint could be served using NGINX or directly implemented within the Web API.
